### ISSUE TITLE
getConnectionAsync throws ConnectionClosed synchronously

### ISSUE THREAD

**Issue by pepone** [zeroc-ice/ice#1729]
See `TODO` in python Ice/ami test for `getConnectionAsync`, this exception was previously throw asynchronously when python extension used the old C++98 mapping.

**Comment by externl** [comment]
I don't see a todo as of https://github.com/zeroc-ice/ice/blob/40171af6057781f3fd07817c02875cebd525df54/python/test/Ice/ami/AllTests.py 

Is this still relevant?

**Comment by externl** [comment]
Maybe fixed by #2489?

**Comment by pepone** [comment]
I fixes TODO in #2489, but I think there is still an issue with NoEndpointException throw synchronously from getConnectionAsync.
