### ISSUE TITLE
JavaScript Ice/timeout hang

### ISSUE THREAD

**Issue by bentoi** [zeroc-ice/ice#200]
The Ice/timeout test hangs from time to time with dist testing on Safari (macOS Sierra) and IE (Windows 10). The hang occurs in the "testing timeout overrides..." test.

**Comment by pepone** [comment]
I was able to reproduce this in the test Windows test VM, the IE debugger doesn't provide any info on why it hangs, attached to the server show no pending invocations.

I kill the server and see the JS controller `waitSuccess` fails with the following exception.

```
stack	"Error: test failed\n   at test (http://127.0.0.1:8080/test/es5/Common/TestHelper.js:176:21)\n   
at _callee2$ (http://127.0.0.1:8080/test/es5/Ice/timeout/Client.js:620:37)\n   
at tryCatch (http://127.0.0.1:8080/node_modules/babel-polyfill/dist/polyfill.js:6900:7)\n   
at invoke (http://127.0.0.1:8080/node_modules/babel-polyfill/dist/polyfill.js:7138:9)\n   
at prototype[method] (http://127.0.0.1:8080/node_modules/babel-polyfill/dist/polyfill.js:6952:9)\n   
at step (http://127.0.0.1:8080/test/es5/Ice/timeout/Client.js:5:172)\n   
at Anonymous function (http://127.0.0.1:8080/test/es5/Ice/timeout/Client.js:5:361)\n   
at run (http://127.0.0.1:8080/node_modules/babel-polyfill/dist/polyfill.js:4294:25)\n   
at Anonymous function (http://127.0.0.1:8080/node_modules/babel-polyfill/dist/polyfill.js:4308:12)\n   
at flush (http://127.0.0.1:8080/node_modules/babel-polyfill/dist/polyfill.js:1398:9)"
```

My understanding is that the client hang is happening on communicator destroy at https://github.com/zeroc-ice/ice/blob/f4a1b1c979ee1c5e7df7e4ccde1b2a0f92a15dcc/js/test/Ice/timeout/Client.js#L343

destroy succeed after killing the server and then the test fails at https://github.com/zeroc-ice/ice/blob/f4a1b1c979ee1c5e7df7e4ccde1b2a0f92a15dcc/js/test/Ice/timeout/Client.js#L345

So far I was not able to reproduce the issue with my local Windows or MacOS machines, just with the test VM.

**Comment by pepone** [comment]
Push a fix to Ice/timeout test that should solve the issue, seems there is a similar issue with hold test but I was unable to reproduce.

**Comment by bentoi** [comment]
The hold test still hangs regularly with the distribution testing on the sierra VM with Safari.

**Comment by pepone** [comment]
Added some tracing and hold seems to hang in the close connection in

https://github.com/zeroc-ice/ice/blob/02fe1dc81595a27f948022b20f098fb1828e00cb/js/test/Ice/hold/Client.js#L227

Seems to only happen with using WSS and es5

**Comment by pepone** [comment]
https://github.com/zeroc-ice/ice/blob/cf720c9de22ea553aa56b94d150baee01e286a3f/js/src/Ice/ConnectionI.js#L267-L272

setImediate callback is not being fired in Safari when running with workers. I'm fixing the timer implementation to not use setImeidate with Safari workers
